+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
Python 3.11.6
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Sat Feb 15 13:43:25 2025 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL iSulad
+ pkgs=iSulad
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs iSulad --node 1 --tempfile ''
Sat Feb 15 13:43:32 2025 - INFO  - pkgs:(iSulad) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ cp /etc/isulad/daemon.json /etc/isulad/daemon.json.bak
cp: cannot stat '/etc/isulad/daemon.json': No such file or directory
+ '[' riscv64 == riscv64 ']'
+ sed -i '/registry-mirrors/a\"https:\/\/docker.io\"' /etc/isulad/daemon.json
sed: can't read /etc/isulad/daemon.json: No such file or directory
+ systemctl restart isulad.service
Job for isulad.service failed because the control process exited with error code.
See "systemctl status isulad.service" and "journalctl -xeu isulad.service" for details.
+ isula pull busybox
Image "busybox" pulling
Can not connect with server.Is the iSulad daemon running on the host?
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Sat Feb 15 13:43:34 2025 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Feb 15 13:43:34 2025 - INFO  - Start to run test.
+ isula run -itd busybox /bin/sh -c 'while true;do echo hello world;sleep 1;done'
Can not connect with server.Is the iSulad daemon running on the host?
++ isula ps -a
++ grep -vi NAMES
++ awk '{print $NF}'
Can not connect with server.Is the iSulad daemon running on the host?
+ container_id=
+ isula inspect -f '{{.State.Status}}' ''
+ grep -i running
Inspect error: No such object:
+ CHECK_RESULT 1 0 0 'Container startup failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Container startup failed'
+ exit_mode=0
+ '[' -z '1 0 0 Container startup failed' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Container startup failed'
+ LOG_ERROR 'Container startup failed'
+ message='Container startup failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Container startup failed'
Sat Feb 15 13:43:35 2025 - ERROR - Container startup failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iSulad_container04.sh line 41'
+ message='oe_test_iSulad_container04.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_iSulad_container04.sh line 41'
Sat Feb 15 13:43:36 2025 - ERROR - oe_test_iSulad_container04.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ isula logs ''
+ grep -i 'hello world'
Can not connect with server.Is the iSulad daemon running on the host?
+ CHECK_RESULT 1 0 0 'Failed to query logs'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to query logs'
+ exit_mode=0
+ '[' -z '1 0 0 Failed to query logs' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to query logs'
+ LOG_ERROR 'Failed to query logs'
+ message='Failed to query logs'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed to query logs'
Sat Feb 15 13:43:36 2025 - ERROR - Failed to query logs
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iSulad_container04.sh line 43'
+ message='oe_test_iSulad_container04.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_iSulad_container04.sh line 43'
Sat Feb 15 13:43:37 2025 - ERROR - oe_test_iSulad_container04.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ isula top ''
+ CHECK_RESULT 1 0 0 'Process does not exist'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Process does not exist'
+ exit_mode=0
+ '[' -z '1 0 0 Process does not exist' ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Process does not exist'
+ LOG_ERROR 'Process does not exist'
+ message='Process does not exist'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Process does not exist'
Sat Feb 15 13:43:37 2025 - ERROR - Process does not exist
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_iSulad_container04.sh line 45'
+ message='oe_test_iSulad_container04.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_iSulad_container04.sh line 45'
Sat Feb 15 13:43:37 2025 - ERROR - oe_test_iSulad_container04.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Feb 15 13:43:38 2025 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Feb 15 13:43:38 2025 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Sat Feb 15 13:43:38 2025 - INFO  - Start to restore the test environment.
+ isula ps -a
+ grep -vi NAMES
+ awk '{print $NF}'
+ xargs -I '{}' isula stop '{}'
Can not connect with server.Is the iSulad daemon running on the host?
+ isula ps -a
+ grep -vi NAMES
+ awk '{print $NF}'
+ xargs -I '{}' isula rm -f '{}'
Can not connect with server.Is the iSulad daemon running on the host?
+ isula rmi busybox
Can not connect with server.Is the iSulad daemon running on the host?
+ mv -f /etc/isulad/daemon.json.bak /etc/isulad/daemon.json
mv: cannot stat '/etc/isulad/daemon.json.bak': No such file or directory
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Sat Feb 15 13:43:40 2025 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Sat Feb 15 13:43:40 2025 - INFO  - End to restore the test environment.
